### ISSUE TITLE
Examples/detoken.bas: Wrong line numbers

### ISSUE THREAD

**Issue by benchmarko** [Bread80/Amstrad-CPC-BASIC-Source#2]
Hello,

It seem that the output of line numbers (non-pointer) is wrong, e.g. for:
`95 goto 1000`
it prints:
`95 goto 232`

Possible correction:
Replace peek(cur) by fnpeekw(cur) in:
`2300 if token = &1e then print fnnum$(fnpeekw(cur));:cur=cur+2:return:'Line number`

Best regards,
mv

**Comment by Bread80** [comment]
Thanks for the report. Should be fixed now.
